### ISSUE TITLE
Remove "PyPi legacy" instructions

### ISSUE THREAD

**Issue by Onager** [log2timeline/l2tdocs#26]
The "PyPi legacy" section on https://github.com/log2timeline/l2tdocs/blob/master/process/PyPI.md looks like it can be removed.

**Comment by joachimmetz** [comment]
They can, I kept them for now since pypi was migrating when I added them.

**Comment by joachimmetz** [comment]
@Onager it is unclear to me what you mean with "clarify" in this context, hence I've reworded the issue title.

Changes to remove "PyPi legacy" instructions https://github.com/log2timeline/l2tdocs/pull/39
