### ISSUE TITLE
Clarify l2tbinaries page

### ISSUE THREAD

**Issue by Onager** [log2timeline/l2tdocs#27]
https://github.com/log2timeline/l2tdocs/blob/master/process/l2tbinaries.md

- [ ] Add a section for updating master from dev
- [ ] Remove reference to "updating testing from dev"?
- [ ] Clarify which branch the commands under "Promoting binary package files from testing to dev" apply to

**Comment by joachimmetz** [comment]
@Onager various changes to the l2tbinaries page have been made starting with https://github.com/log2timeline/l2tdocs/commit/ca69b753ace91369d8b486fdc9f2e1ada5b634f9

Assigning this issue to you to assess and indicate what "clarify" means in your perspective.

**Comment by joachimmetz** [comment]
@Onager friendly ping, it looks like some of your to dos have been addressed in the mean time. Could you check and close this issue if no longer relevant.

**Comment by joachimmetz** [comment]
No response closing issue
