### ISSUE TITLE
Detail the l2tbinaries & dependencies packaging/releasing process

### ISSUE THREAD

**Issue by rgayon** [log2timeline/l2tdocs#8]
Would love to have:
+ schema and magical commands to push new packages to l2tbinaries:
  + dev => testing => master for the mac/win32/win64
    * https://codereview.appspot.com/323460043/
+ For linuxes
  + Ubuntu : move gift ppa doc here
    * https://github.com/log2timeline/l2tdocs/blob/master/process/GIFT%20PPA.md
  + Fedora
    * https://codereview.appspot.com/322520043/
  + Debian ?

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/323460043
